version: '3'

services:
  reverse-proxy:
    image: traefik:v2.10
    command: 
      - --api.insecure=true 
      - --providers.docker 
      - --providers.docker.exposedbydefault=false 
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock

  whoami:
    image: traefik/whoami
    labels:
      - "traefik.enable=true" 
      - "traefik.http.routers.whoami.entrypoints=http" 
      - "traefik.http.routers.whoami.rule=Host(`whoami.midominio.internal`)"

  moodle:
    image: bitnami/moodle
    restart: always
    environment:
      - MOODLE_URL=http://moodle.gassin.internal
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.moodle.entrypoints=http"
      - "traefik.http.routers.moodle.rule=Host(`moodle.gassin.internal`)"

  