controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_listador:
    path: /listar
    controller: App\Controller\ListadorController::listar