version: "3.3"

services:

  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      #- "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  whoami:
    image: "traefik/whoami"
    container_name: "simple-service"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"
      - "traefik.http.routers.whoami.entrypoints=web"

  asteroides:
    image: "gassindev/juego-asteroides"
    container_name: "juegoAsteroides"
    restart: always
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.asteroides.rule=Host(`web.gassin.internal`)"
      - "traefik.http.routers.asteroides.entrypoints=web"

  joomla:
    image: joomla
    restart: always
    links:
      - joomladb:mysql
    environment:
      JOOMLA_DB_HOST: joomladb
      JOOMLA_DB_PASSWORD: example
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.joomla.rule=Host(`joomla.gassin.internal`)"
      - "traefik.http.routers.joomla.entrypoints=web"

  joomladb:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example